// Generated by CoffeeScript 1.6.3
define(function(require) {
  var Color;
  Color = require('helpers/color');
  return (function() {
    return {
      darken: function(colorVal, percent) {
        var color;
        if (!percent) {
          percent = 10;
        }
        color = new Color(colorVal);
        return color.adjust(percent).toHex();
      },
      lighten: function(color, percent) {
        return this.darken(color, -percent);
      }
    };
  })();
});
