// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['backbone', 'models/palette', 'backbone.localStorage'], function(Backbone, PatternModel) {
  var PatternsCollection, _ref;
  return PatternsCollection = (function(_super) {
    __extends(PatternsCollection, _super);

    function PatternsCollection() {
      _ref = PatternsCollection.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    PatternsCollection.prototype.model = PatternModel;

    PatternsCollection.prototype.url = new Backbone.LocalStorage("IntarsiaPatterns");

    return PatternsCollection;

  })(Backbone.Collection);
});
