// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['backbone', 'models/stitch'], function(Backbone, StitchModel) {
  var StitchesCollection, _ref;
  return StitchesCollection = (function(_super) {
    __extends(StitchesCollection, _super);

    function StitchesCollection() {
      _ref = StitchesCollection.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    StitchesCollection.prototype.model = StitchModel;

    return StitchesCollection;

  })(Backbone.Collection);
});
