// Generated by CoffeeScript 1.6.3
var _ref,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Intarsia.Views.Stitch = (function(_super) {
  __extends(Stitch, _super);

  function Stitch() {
    this.reset = __bind(this.reset, this);
    this.setBrushColor = __bind(this.setBrushColor, this);
    this.setDragging = __bind(this.setDragging, this);
    this.paintContinuous = __bind(this.paintContinuous, this);
    this.recolor = __bind(this.recolor, this);
    this.paintStitch = __bind(this.paintStitch, this);
    _ref = Stitch.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  Stitch.prototype.tagName = 'div';

  Stitch.prototype.className = 'stitch-holder';

  Stitch.prototype.template = $('#stitch-template').html();

  Stitch.prototype.defaults = function() {
    return {
      color: 'default'
    };
  };

  Stitch.prototype.events = {
    'mousedown': 'paintStitch',
    'mouseenter': 'paintContinuous'
  };

  Stitch.prototype.initialize = function(options) {
    this.options = _.extend({}, this.defaults(), options);
    this.brushColor = this.defaultColor = this.defaults().color;
    this.dragging = false;
    this.listenTo(this.model, 'change:color', this.recolor, this);
    this.listenTo(events, 'swatch:select', this.setBrushColor);
    this.listenTo(events, 'mouse:dragging', this.setDragging);
    return this.listenTo(events, 'pattern:reset', this.reset);
  };

  Stitch.prototype.paintStitch = function(evt) {
    return this.model.paint(this.brushColor);
  };

  Stitch.prototype.recolor = function() {
    return this.$el.find('.stitch').removeClass().addClass("stitch " + (this.model.get('color')));
  };

  Stitch.prototype.paintContinuous = function() {
    if (this.dragging) {
      return this.paintStitch();
    }
  };

  Stitch.prototype.setDragging = function(dragging) {
    return this.dragging = dragging;
  };

  Stitch.prototype.setBrushColor = function(color) {
    return this.brushColor = color;
  };

  Stitch.prototype.reset = function(evt) {
    return this.model.erase();
  };

  Stitch.prototype.render = function() {
    this.$el.html(this.template);
    this.recolor();
    return this;
  };

  return Stitch;

})(Backbone.View);
