// Generated by CoffeeScript 1.6.3
var _ref,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Intarsia.Views.Swatches = (function(_super) {
  __extends(Swatches, _super);

  function Swatches() {
    this.addOne = __bind(this.addOne, this);
    _ref = Swatches.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  Swatches.prototype.tagName = 'ul';

  Swatches.prototype.className = 'intarsia-palette clearfix';

  Swatches.prototype.initialize = function(options) {
    this.collection.on('reset', this.addAll);
    return this.listenTo(events, 'pattern:reset', this.addAll);
  };

  Swatches.prototype.setDefaultColor = function() {
    return this.$el.children(":first").find('a').click();
  };

  Swatches.prototype.removeItemViews = function() {
    return events.trigger('swatch:remove');
  };

  Swatches.prototype.addOne = function(item) {
    var view;
    view = new Intarsia.Views.Swatch({
      model: item
    });
    return this.$el.append(view.render().el);
  };

  Swatches.prototype.addAll = function() {
    this.removeItemViews();
    this.collection.each(this.addOne, this);
    return this.setDefaultColor();
  };

  Swatches.prototype.remove = function() {
    this.removeItemViews();
    return Swatches.__super__.remove.call(this);
  };

  Swatches.prototype.render = function() {
    this.addAll();
    return this;
  };

  return Swatches;

})(Backbone.View);
