// Generated by CoffeeScript 1.6.3
var _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Intarsia.Views.Swatch = (function(_super) {
  __extends(Swatch, _super);

  function Swatch() {
    _ref = Swatch.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  Swatch.prototype.events = {
    'mousedown': 'setColor'
  };

  return Swatch;

})(Backbone.Views);
