// Generated by CoffeeScript 1.6.3
var _ref, _ref1,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Intarsia.Models.Palette = (function(_super) {
  __extends(Palette, _super);

  function Palette() {
    _ref = Palette.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  Palette.prototype.defaults = function() {
    return {
      name: 'My Palette',
      colors: ['red', 'orange', 'yellow', 'green', 'blue', 'navy', 'purple', 'white', 'silver', 'grey', 'black', 'default']
    };
  };

  Palette.prototype.initialize = function() {
    return this.options = _.extend({}, this.defaults(), this.options);
  };

  return Palette;

})(Backbone.Model);

Intarsia.Collections.Palettes = (function(_super) {
  __extends(Palettes, _super);

  function Palettes() {
    _ref1 = Palettes.__super__.constructor.apply(this, arguments);
    return _ref1;
  }

  Palettes.prototype.model = Intarsia.Models.Palette;

  return Palettes;

})(Backbone.Collection);
