// Generated by CoffeeScript 1.6.3
define(function(require) {
  var ColorString;
  return ColorString = (function() {
    function ColorString(color) {
      this.color = color;
    }

    ColorString.prototype.toColor = function() {
      if (this.isHex()) {
        return this.hexToColor();
      } else if (this.isRgb()) {
        return this.rgbToColor();
      } else {
        return false;
      }
    };

    ColorString.prototype.isHex = function() {
      return /^#?([a-f\d]){6}$/i.test(this.color);
    };

    ColorString.prototype.isRgb = function() {
      return /rgb(a){0,1}\((\d{1,3})(,( ){0,1}(\d{1,3})){2,3}\)/.test(this.color);
    };

    ColorString.prototype.hexToColor = function() {
      var hex;
      hex = parseInt(this.color.replace(/^#/, ''), 16);
      return {
        r: (hex >> 16) & 255,
        g: (hex >> 8) & 255,
        b: hex & 255
      };
    };

    ColorString.prototype.rgbToColor = function() {
      var colorValues;
      colorValues = this.color.match(/\d+/g);
      return {
        r: colorValues[0],
        g: colorValues[1],
        b: colorValues[2]
      };
    };

    return ColorString;

  })();
});
