// Generated by CoffeeScript 1.6.3
define(function(require) {
  var Color;
  return Color = (function() {
    function Color(color) {
      this.color = color;
    }

    Color.prototype.adjustChannel = function(channel, percent) {
      var newChannel;
      newChannel = parseInt(channel * (100 - percent) / 100);
      if (newChannel > 255) {
        newChannel = 255;
      }
      if (newChannel < 0) {
        newChannel = 0;
      }
      return newChannel;
    };

    Color.prototype.adjust = function(percent) {
      var c, _i, _len, _ref;
      _ref = ['r', 'g', 'b'];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        c = _ref[_i];
        this.color[c] = this.adjustChannel(this.color[c], percent);
      }
      return this;
    };

    Color.prototype.toRgb = function() {
      return "rgb(" + this.color.r + ", " + this.color.g + ", " + this.color.b + ")";
    };

    Color.prototype.toHex = function() {
      var hex;
      hex = (1 << 24) + (this.color.r << 16) + (this.color.g << 8) + this.color.b;
      return "#" + hex.toString(16).slice(1);
    };

    return Color;

  })();
});
