// Generated by CoffeeScript 1.6.3
define(function(require) {
  var Color, ColorString;
  Color = require('helpers/color');
  ColorString = require('helpers/color_string');
  return (function() {
    return {
      darken: function(colorVal, percent) {
        var color, colorObj, colorStr;
        if (percent == null) {
          percent = percent || 10;
        }
        colorStr = new ColorString(colorVal);
        colorObj = colorStr.toColor();
        if (!colorObj) {
          return colorVal;
        }
        color = new Color(colorObj);
        return color.adjust(percent).toHex();
      },
      lighten: function(color, percent) {
        return this.darken(color, -percent);
      }
    };
  })();
});
