// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['underscore', 'backbone'], function(_, Backbone) {
  var PatternModel, _ref;
  return PatternModel = (function(_super) {
    __extends(PatternModel, _super);

    function PatternModel() {
      _ref = PatternModel.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    PatternModel.prototype.defaults = function() {
      return {
        name: 'My Pattern',
        width: 30,
        height: 20,
        grid: []
      };
    };

    PatternModel.prototype.initialize = function(options) {
      return this.options = _.extend({}, this.defaults(), options);
    };

    return PatternModel;

  })(Backbone.Model);
});
