// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['backbone', 'underscore'], function(Backbone, _) {
  var StitchModel, _ref;
  return StitchModel = (function(_super) {
    __extends(StitchModel, _super);

    function StitchModel() {
      _ref = StitchModel.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    StitchModel.prototype.defaults = function() {
      return {
        color: 'default',
        row: 0
      };
    };

    StitchModel.prototype.initialize = function(options) {
      return this.options = _.extend({}, this.defaults(), options);
    };

    StitchModel.prototype.paint = function(color) {
      if (this.get('color') === color) {
        return this.erase();
      } else {
        return this.set({
          color: color
        });
      }
    };

    StitchModel.prototype.erase = function() {
      return this.set({
        color: this.defaults().color
      });
    };

    return StitchModel;

  })(Backbone.Model);
});
