// Generated by CoffeeScript 1.6.3
define(function(require) {
  var Backbone, _;
  _ = require('underscore');
  Backbone = require('backbone');
  return (function() {
    var options;
    return options = {
      baseColor: '#fcfcfc',
      vent: _.extend({}, Backbone.Events)
    };
  })();
});
