// Generated by CoffeeScript 1.6.3
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['jquery', 'backbone', 'models/pattern', 'views/pattern/pattern', 'views/pattern/forms/create'], function($, Backbone, PatternModel, PatternView, PatternCreateView) {
  var AppRouter, _ref;
  return AppRouter = (function(_super) {
    __extends(AppRouter, _super);

    function AppRouter() {
      this.index = __bind(this.index, this);
      _ref = AppRouter.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    AppRouter.prototype.el = $('#intarsia');

    AppRouter.prototype.routes = {
      'patterns/new': 'newPattern',
      '*action': 'index'
    };

    AppRouter.prototype.index = function() {
      var pattern, patternView;
      pattern = new PatternModel({
        "name": "My awesome pattern",
        "width": 40,
        "height": 30,
        "grid": [
          [
            {
              "color": "red"
            }, {
              "color": "green"
            }, {
              "color": "default"
            }, {
              "color": "blue"
            }, {
              "color": "default"
            }, {
              "color": "default"
            }, {
              "color": "yellow"
            }, {
              "color": "default"
            }, {
              "color": "default"
            }, {
              "color": "default"
            }
          ], [
            {
              "color": "default"
            }, {
              "color": "default"
            }, {
              "color": "default"
            }, {
              "color": "default"
            }, {
              "color": "default"
            }, {
              "color": "default"
            }, {
              "color": "default"
            }, {
              "color": "default"
            }, {
              "color": "default"
            }, {
              "color": "default"
            }
          ], [
            {
              "color": "default"
            }, {
              "color": "default"
            }, {
              "color": "default"
            }, {
              "color": "default"
            }, {
              "color": "default"
            }, {
              "color": "default"
            }, {
              "color": "default"
            }, {
              "color": "default"
            }, {
              "color": "default"
            }, {
              "color": "default"
            }
          ]
        ]
      });
      patternView = new PatternView({
        model: pattern
      });
      return this.el.append(patternView.render().el);
    };

    AppRouter.prototype.newPattern = function() {
      var appView;
      appView = new PatternCreateView();
      return this.el.append(appView.render().el);
    };

    return AppRouter;

  })(Backbone.Router);
});
