// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['backbone', 'underscore'], function(Backbone, _) {
  var SwatchModel, _ref;
  return SwatchModel = (function(_super) {
    __extends(SwatchModel, _super);

    function SwatchModel() {
      _ref = SwatchModel.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    SwatchModel.prototype.defaults = function() {
      return {
        color: 'default'
      };
    };

    SwatchModel.prototype.initialize = function(options) {
      return this.options = _.extend({}, this.defaults(), options);
    };

    return SwatchModel;

  })(Backbone.Model);
});
