// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['jquery', 'backbone', 'app', 'handlebars', 'text!templates/pattern_edit_form.html'], function($, Backbone, App, Handlebars, template) {
  var PatternFormEditView, _ref;
  return PatternFormEditView = (function(_super) {
    __extends(PatternFormEditView, _super);

    function PatternFormEditView() {
      _ref = PatternFormEditView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    PatternFormEditView.prototype.className = 'intarsia-pattern-form';

    PatternFormEditView.prototype.template = Handlebars.compile(template);

    /*events:
      'click #reset': 'reset'
      'click #save': 'save'
    
    save: (evt) =>
      evt.preventDefault()
    
    reset: (evt) =>
      evt.preventDefault()
      App.vent.trigger('pattern:reset')
    */


    PatternFormEditView.prototype.render = function() {
      this.$el.html(this.template(this.model.toJSON()));
      return this;
    };

    return PatternFormEditView;

  })(Backbone.View);
});
