// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['backbone', 'views/pattern'], function(Backbone, PatternView) {
  var AppRouter, _ref;
  return AppRouter = (function(_super) {
    __extends(AppRouter, _super);

    function AppRouter() {
      _ref = AppRouter.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    AppRouter.prototype.routes = {
      '': 'index'
    };

    AppRouter.prototype.index = function() {
      var pattern;
      return pattern = new PatternView({
        el: '#intarsia',
        width: 30,
        height: 30
      });
    };

    return AppRouter;

  })(Backbone.Router);
});
