// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['jquery', 'backbone', 'vent', 'collections/swatches', 'views/swatches', 'models/palette'], function($, Backbone, AppEvents, SwatchesCollection, SwatchesView, PaletteModel) {
  var PaletteView, _ref;
  return PaletteView = (function(_super) {
    __extends(PaletteView, _super);

    function PaletteView() {
      _ref = PaletteView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    PaletteView.prototype.model = new PaletteModel;

    PaletteView.prototype.tagName = 'div';

    PaletteView.prototype.className = 'intarsia-palette-holder';

    PaletteView.prototype.initialize = function(options) {
      var color, colors;
      console.log(this.model);
      colors = (function() {
        var _i, _len, _ref1, _results;
        _ref1 = this.model.options.colors;
        _results = [];
        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
          color = _ref1[_i];
          _results.push({
            color: color
          });
        }
        return _results;
      }).call(this);
      this.palette = new SwatchesView({
        collection: new SwatchesCollection(colors)
      });
      return this.listenTo(AppEvents, 'pattern:reset', this.reset);
    };

    PaletteView.prototype.setDefaultColor = function() {
      return this.palette.setDefaultColor();
    };

    PaletteView.prototype.render = function() {
      this.$el.prepend(this.palette.render().el);
      return this;
    };

    return PaletteView;

  })(Backbone.View);
});
