// Generated by CoffeeScript 1.6.3
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['jquery', 'backbone', 'vent'], function($, Backbone, AppEvents) {
  var PatternFormView, _ref;
  return PatternFormView = (function(_super) {
    __extends(PatternFormView, _super);

    function PatternFormView() {
      this.reset = __bind(this.reset, this);
      _ref = PatternFormView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    PatternFormView.prototype.events = {
      'click #reset': 'reset'
    };

    PatternFormView.prototype.reset = function(evt) {
      console.log("form reset");
      return AppEvents.trigger('pattern:reset');
    };

    return PatternFormView;

  })(Backbone.View);
});
